# Generated by Django 3.1.5 on 2021-01-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstSlideIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='siteview/firstslideindex/images', verbose_name='image')),
                ('detail', models.CharField(max_length=500, verbose_name='product detail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'FirstSlideIndex',
                'verbose_name_plural': 'FirstSlideIndex',
            },
        ),
    ]
