# Generated by Django 3.1.5 on 2021-01-21 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstslideindex',
            name='publish_time',
            field=models.DateTimeField(db_index=True, default=datetime.date, verbose_name='Publish at'),
            preserve_default=False,
        ),
    ]
