# Generated by Django 3.1.5 on 2021-01-24 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteview', '0002_firstslideindex_publish_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstslideindex',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='firstslideindex',
            name='publish_time',
        ),
        migrations.RemoveField(
            model_name='firstslideindex',
            name='updated_at',
        ),
    ]
