# Generated by Django 3.1.5 on 2021-01-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteview', '0003_auto_20210124_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstslideindex',
            name='title_one',
            field=models.CharField(default=1, max_length=500, verbose_name='product title one'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstslideindex',
            name='title_two',
            field=models.CharField(default=1, max_length=500, verbose_name='product title two'),
            preserve_default=False,
        ),
    ]
