# Generated by Django 3.1.5 on 2021-01-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteview', '0004_auto_20210124_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstslideindex',
            name='draft',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Draft'),
        ),
    ]
