# Generated by Django 3.1.5 on 2021-01-25 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Address', related_query_name='Address', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
