# Generated by Django 3.1.5 on 2021-01-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20210125_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='discription',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='discription'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/shop/images', verbose_name='image'),
        ),
    ]
