# Generated by Django 3.1.5 on 2021-02-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20210130_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='facebook',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='shop',
            name='instagram',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='instagram'),
        ),
        migrations.AddField(
            model_name='shop',
            name='telegram',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='telegram'),
        ),
        migrations.AddField(
            model_name='shop',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='whatsapp'),
        ),
    ]
