# Generated by Django 3.1.5 on 2021-02-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20210202_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='publish_time',
        ),
        migrations.AddField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
