# Generated by Django 3.1.5 on 2021-04-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_auto_20210206_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='city name'),
        ),
    ]
