# Generated by Django 3.1.5 on 2021-04-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=500, verbose_name='place name'),
        ),
    ]
