# Generated by Django 3.1.5 on 2021-05-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_auto_20210403_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='discription',
            field=models.TextField(blank=True, null=True, verbose_name='discription'),
        ),
    ]
