# Generated by Django 3.1.5 on 2021-05-16 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_auto_20210508_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-id'], 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterUniqueTogether(
            name='shop',
            unique_together={('user',)},
        ),
    ]
