# Generated by Django 3.1.5 on 2021-05-26 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('ordered', models.BooleanField(default=False, verbose_name='Ordered')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Basket', related_query_name='Basket', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Basket',
                'verbose_name_plural': 'Baskets',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('basket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Basket', related_query_name='Basket', to='Orders.basket', verbose_name='Orders')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Orders', related_query_name='Orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Orders',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Peyment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pey_date', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('orders', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Peyment', related_query_name='Peyment', to='Orders.orders', verbose_name='Orders')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', related_query_name='payment', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='BasketItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False, verbose_name='Ordered')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BasketItems', related_query_name='BasketItems', to='Orders.basket', verbose_name='Basket')),
                ('shopproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BasketItems', related_query_name='BasketItems', to='Products.shopproduct', verbose_name='ShopProduct')),
            ],
        ),
    ]
