# Generated by Django 3.1.5 on 2021-01-25 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0001_initial'),
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='image',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='name',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='products',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='publish_time',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='image',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='products',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='publish_time',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='peyment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='peyment',
            name='publish_time',
        ),
        migrations.RemoveField(
            model_name='peyment',
            name='total_price',
        ),
        migrations.AddField(
            model_name='basket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='orders',
            name='basket',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Basket', related_query_name='Basket', to='Orders.basket', verbose_name='Orders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='peyment',
            name='orders',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Peyment', related_query_name='Peyment', to='Orders.orders', verbose_name='Orders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peyment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Basket', related_query_name='Basket', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Orders', related_query_name='Orders', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='peyment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', related_query_name='payment', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='BasketItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BasketItems', related_query_name='BasketItems', to='Orders.basket', verbose_name='Basket')),
                ('shopproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BasketItems', related_query_name='BasketItems', to='Products.shopproduct', verbose_name='ShopProduct')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='BasketItems', related_query_name='BasketItems', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
