# Generated by Django 3.1.5 on 2021-04-27 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0038_commentdislike'),
        ('Orders', '0006_auto_20210208_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitems',
            name='shopproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BasketItems', related_query_name='BasketItems', to='Products.shopproduct', verbose_name='ShopProduct'),
        ),
    ]
