# Generated by Django 3.1.5 on 2021-01-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20210127_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Brand name'),
        ),
    ]
