# Generated by Django 3.1.5 on 2021-01-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_auto_20210128_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='details',
            field=models.CharField(max_length=5000, verbose_name='Brand details'),
        ),
    ]
