# Generated by Django 3.1.5 on 2021-01-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20210125_1207'),
        ('Products', '0007_auto_20210128_1650'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopproduct',
            unique_together={('shop', 'product')},
        ),
    ]
