# Generated by Django 3.1.5 on 2021-01-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_auto_20210129_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='details',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Brand details'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Products/brand/images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='detail',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='cateqory detail'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Products/category/images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Products/images/images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='product detail'),
        ),
    ]
