# Generated by Django 3.1.5 on 2021-02-02 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_auto_20210130_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='off',
            old_name='number',
            new_name='price',
        ),
    ]
