# Generated by Django 3.1.5 on 2021-02-06 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_auto_20210206_0719'),
        ('Products', '0010_auto_20210202_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='off',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Off', related_query_name='Off', to='Accounts.shop', verbose_name='Shop'),
        ),
    ]
