# Generated by Django 3.1.5 on 2021-02-06 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0015_remove_off_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='off',
            name='shop_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Off', related_query_name='Off', to='Products.shopproduct', verbose_name='Shop_product'),
        ),
    ]
