# Generated by Django 3.1.5 on 2021-02-08 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0017_auto_20210208_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='parent_self',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.shopproduct'),
        ),
    ]
