# Generated by Django 3.1.5 on 2021-02-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0018_shopproduct_parent_self'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='price',
            field=models.PositiveIntegerField(verbose_name='product price'),
        ),
    ]
