# Generated by Django 3.1.5 on 2021-02-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0020_auto_20210208_1935'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopproduct',
            unique_together=set(),
        ),
    ]
