# Generated by Django 3.1.5 on 2021-02-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_auto_20210206_0719'),
        ('Products', '0022_remove_shopproduct_parent_self'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopproduct',
            unique_together={('shop', 'product', 'color', 'size')},
        ),
    ]
