# Generated by Django 3.1.5 on 2021-04-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0024_auto_20210404_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmeta',
            name='text_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='field_title'),
        ),
        migrations.AddField(
            model_name='productmeta',
            name='text_value',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='field_value'),
        ),
    ]
