# Generated by Django 3.1.5 on 2021-04-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0026_auto_20210410_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmeta',
            name='text_title',
            field=models.CharField(max_length=1000, verbose_name='field_title'),
        ),
        migrations.AlterField(
            model_name='productmeta',
            name='text_value',
            field=models.CharField(max_length=1000, verbose_name='field_value'),
        ),
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
