# Generated by Django 3.1.5 on 2021-04-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0029_auto_20210410_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmeta',
            name='text_value',
            field=models.CharField(max_length=5000, verbose_name='field_value'),
        ),
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
