# Generated by Django 3.1.5 on 2021-04-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0031_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={},
        ),
    ]
