# Generated by Django 3.1.5 on 2021-04-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0032_auto_20210410_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'WishList', 'verbose_name_plural': 'WishLists'},
        ),
    ]
