# Generated by Django 3.1.5 on 2021-04-11 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0033_auto_20210410_0959'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
