# Generated by Django 3.1.5 on 2021-04-13 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0037_auto_20210412_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentDisLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislike', models.BooleanField(default=True, verbose_name='dislike')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentDisLike', related_query_name='CommentDisLikes', to='Products.comment', verbose_name='Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentDisLike', related_query_name='CommentDisLikes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'CommentDisLike',
                'unique_together': {('user', 'comment')},
            },
        ),
    ]
