# Generated by Django 3.1.5 on 2021-05-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0039_product_is_amazing_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='برند ویژه'),
        ),
    ]
