# Generated by Django 3.1.5 on 2021-05-09 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0040_brand_is_special'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
