# Generated by Django 3.1.5 on 2021-05-16 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0043_auto_20210513_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-id'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-id'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
