# Generated by Django 3.1.5 on 2021-05-16 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_auto_20210516_1155'),
        ('Products', '0045_auto_20210516_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Image', related_query_name='Image', to='Accounts.shop', verbose_name='Shop'),
        ),
    ]
