# Generated by Django 3.1.5 on 2021-05-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0047_auto_20210516_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
    ]
