# Generated by Django 3.1.5 on 2021-05-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0048_image_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentdislike',
            old_name='dislike',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='like',
            new_name='is_active',
        ),
    ]
