# Generated by Django 3.1.5 on 2021-05-18 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0049_auto_20210516_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-id'], 'verbose_name': 'WishList', 'verbose_name_plural': 'WishLists'},
        ),
    ]
